(source gnu)
(source melpa)
(source marmalade)

; コメントアウトは便利そうだけど学習速度上の理由でまだ入れてないもの
(depends-on "auto-complete")
(depends-on "cask")
(depends-on "color-theme")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "fringe-helper")
(depends-on "git-gutter-fringe")
(depends-on "helm")
(depends-on "htmlize")
(depends-on "init-loader")
;(depends-on "magit")
;(depends-on "multiple-cursors")
(depends-on "nlinum")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "pbcopy")
(depends-on "pkg-info")
(depends-on "popwin")
;(depends-on "prodigy")
;(depends-on "quickrun")
;(depends-on "s")
(depends-on "undo-tree")
(depends-on "web-mode")
;(depends-on "yasnippet")

;; prog mode
;python
(depends-on "python-mode")
(depends-on "python-pylint")
;haskell
(depends-on "haskell-mode")
;(depends-on "flycheck-haskell")
